<?php

/**
 * BaseAmShopCategoryOptionConn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $category_id
 * @property integer $option_id
 * @property AmShopCategory $AmShopCategory
 * @property AmShopOption $AmShopOption
 * 
 * @method integer                  getCategoryId()     Returns the current record's "category_id" value
 * @method integer                  getOptionId()       Returns the current record's "option_id" value
 * @method AmShopCategory           getAmShopCategory() Returns the current record's "AmShopCategory" value
 * @method AmShopOption             getAmShopOption()   Returns the current record's "AmShopOption" value
 * @method AmShopCategoryOptionConn setCategoryId()     Sets the current record's "category_id" value
 * @method AmShopCategoryOptionConn setOptionId()       Sets the current record's "option_id" value
 * @method AmShopCategoryOptionConn setAmShopCategory() Sets the current record's "AmShopCategory" value
 * @method AmShopCategoryOptionConn setAmShopOption()   Sets the current record's "AmShopOption" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmShopCategoryOptionConn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_shop_category_option_conn');
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmShopCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('AmShopOption', array(
             'local' => 'option_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}