<?php

/**
 * BaseAmObjectType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $object_model_name
 * @property string $object_table_name
 * @property string $body
 * @property string $sentence_format
 * @property Doctrine_Collection $AmActions
 * @property AmObjectActionConn $AmObjectActionConn
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getObjectModelName()    Returns the current record's "object_model_name" value
 * @method string              getObjectTableName()    Returns the current record's "object_table_name" value
 * @method string              getBody()               Returns the current record's "body" value
 * @method string              getSentenceFormat()     Returns the current record's "sentence_format" value
 * @method Doctrine_Collection getAmActions()          Returns the current record's "AmActions" collection
 * @method AmObjectActionConn  getAmObjectActionConn() Returns the current record's "AmObjectActionConn" value
 * @method AmObjectType        setId()                 Sets the current record's "id" value
 * @method AmObjectType        setName()               Sets the current record's "name" value
 * @method AmObjectType        setObjectModelName()    Sets the current record's "object_model_name" value
 * @method AmObjectType        setObjectTableName()    Sets the current record's "object_table_name" value
 * @method AmObjectType        setBody()               Sets the current record's "body" value
 * @method AmObjectType        setSentenceFormat()     Sets the current record's "sentence_format" value
 * @method AmObjectType        setAmActions()          Sets the current record's "AmActions" collection
 * @method AmObjectType        setAmObjectActionConn() Sets the current record's "AmObjectActionConn" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmObjectType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_object_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('object_model_name', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('object_table_name', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('sentence_format', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmAction as AmActions', array(
             'refClass' => 'AmObjectActionConn',
             'local' => 'object_type_id',
             'foreign' => 'action_id'));

        $this->hasOne('AmObjectActionConn', array(
             'local' => 'id',
             'foreign' => 'object_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}