<?php

/**
 * BaseAmEvent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $body
 * @property integer $group_id
 * @property date $when_date
 * @property time $when_hour
 * @property string $place
 * @property string $location
 * @property boolean $is_blocked
 * @property AmGroup $AmGroup
 * 
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getBody()       Returns the current record's "body" value
 * @method integer getGroupId()    Returns the current record's "group_id" value
 * @method date    getWhenDate()   Returns the current record's "when_date" value
 * @method time    getWhenHour()   Returns the current record's "when_hour" value
 * @method string  getPlace()      Returns the current record's "place" value
 * @method string  getLocation()   Returns the current record's "location" value
 * @method boolean getIsBlocked()  Returns the current record's "is_blocked" value
 * @method AmGroup getAmGroup()    Returns the current record's "AmGroup" value
 * @method AmEvent setName()       Sets the current record's "name" value
 * @method AmEvent setBody()       Sets the current record's "body" value
 * @method AmEvent setGroupId()    Sets the current record's "group_id" value
 * @method AmEvent setWhenDate()   Sets the current record's "when_date" value
 * @method AmEvent setWhenHour()   Sets the current record's "when_hour" value
 * @method AmEvent setPlace()      Sets the current record's "place" value
 * @method AmEvent setLocation()   Sets the current record's "location" value
 * @method AmEvent setIsBlocked()  Sets the current record's "is_blocked" value
 * @method AmEvent setAmGroup()    Sets the current record's "AmGroup" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmEvent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_event');
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('when_date', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('when_hour', 'time', 25, array(
             'type' => 'time',
             'length' => 25,
             ));
        $this->hasColumn('place', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('location', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_blocked', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}