<?php

/**
 * BaseAmMessage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $created_user_id
 * @property integer $sended_user_count
 * @property string $name
 * @property string $body
 * @property Doctrine_Collection $AmUsers
 * @property AmUserMessageConn $AmUserMessageConn
 * 
 * @method integer             getCreatedUserId()     Returns the current record's "created_user_id" value
 * @method integer             getSendedUserCount()   Returns the current record's "sended_user_count" value
 * @method string              getName()              Returns the current record's "name" value
 * @method string              getBody()              Returns the current record's "body" value
 * @method Doctrine_Collection getAmUsers()           Returns the current record's "AmUsers" collection
 * @method AmUserMessageConn   getAmUserMessageConn() Returns the current record's "AmUserMessageConn" value
 * @method AmMessage           setCreatedUserId()     Sets the current record's "created_user_id" value
 * @method AmMessage           setSendedUserCount()   Sets the current record's "sended_user_count" value
 * @method AmMessage           setName()              Sets the current record's "name" value
 * @method AmMessage           setBody()              Sets the current record's "body" value
 * @method AmMessage           setAmUsers()           Sets the current record's "AmUsers" collection
 * @method AmMessage           setAmUserMessageConn() Sets the current record's "AmUserMessageConn" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmMessage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_message');
        $this->hasColumn('created_user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sended_user_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 1,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmUser as AmUsers', array(
             'refClass' => 'AmUserMessageConn',
             'local' => 'message_id',
             'foreign' => 'user_id'));

        $this->hasOne('AmUserMessageConn', array(
             'local' => 'id',
             'foreign' => 'message_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}