<?php

/**
 * BaseAmAccess
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property string $slug
 * @property Doctrine_Collection $AmPhotoAlbum
 * @property Doctrine_Collection $AmVideo
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getBody()         Returns the current record's "body" value
 * @method string              getSlug()         Returns the current record's "slug" value
 * @method Doctrine_Collection getAmPhotoAlbum() Returns the current record's "AmPhotoAlbum" collection
 * @method Doctrine_Collection getAmVideo()      Returns the current record's "AmVideo" collection
 * @method AmAccess            setId()           Sets the current record's "id" value
 * @method AmAccess            setName()         Sets the current record's "name" value
 * @method AmAccess            setBody()         Sets the current record's "body" value
 * @method AmAccess            setSlug()         Sets the current record's "slug" value
 * @method AmAccess            setAmPhotoAlbum() Sets the current record's "AmPhotoAlbum" collection
 * @method AmAccess            setAmVideo()      Sets the current record's "AmVideo" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmAccess extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_access');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('slug', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmPhotoAlbum', array(
             'local' => 'id',
             'foreign' => 'access_id'));

        $this->hasMany('AmVideo', array(
             'local' => 'id',
             'foreign' => 'access_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}