<?php

/**
 * BaseAmWhere
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $object_type_id
 * @property integer $object_id
 * @property string $sentence_format
 * @property integer $group_id
 * @property AmGroup $AmGroup
 * @property Doctrine_Collection $AmActivityLogs
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getObjectTypeId()    Returns the current record's "object_type_id" value
 * @method integer             getObjectId()        Returns the current record's "object_id" value
 * @method string              getSentenceFormat()  Returns the current record's "sentence_format" value
 * @method integer             getGroupId()         Returns the current record's "group_id" value
 * @method AmGroup             getAmGroup()         Returns the current record's "AmGroup" value
 * @method Doctrine_Collection getAmActivityLogs()  Returns the current record's "AmActivityLogs" collection
 * @method AmWhere             setId()              Sets the current record's "id" value
 * @method AmWhere             setObjectTypeId()    Sets the current record's "object_type_id" value
 * @method AmWhere             setObjectId()        Sets the current record's "object_id" value
 * @method AmWhere             setSentenceFormat()  Sets the current record's "sentence_format" value
 * @method AmWhere             setGroupId()         Sets the current record's "group_id" value
 * @method AmWhere             setAmGroup()         Sets the current record's "AmGroup" value
 * @method AmWhere             setAmActivityLogs()  Sets the current record's "AmActivityLogs" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmWhere extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_where');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('object_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('object_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sentence_format', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasMany('AmActivityLog as AmActivityLogs', array(
             'local' => 'id',
             'foreign' => 'where_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}