<?php

/**
 * BaseAmSmsLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $mobile_number
 * @property string $message
 * @property string $sended_date
 * @property integer $activity_log_id
 * 
 * @method string   getMobileNumber()    Returns the current record's "mobile_number" value
 * @method string   getMessage()         Returns the current record's "message" value
 * @method string   getSendedDate()      Returns the current record's "sended_date" value
 * @method integer  getActivityLogId()   Returns the current record's "activity_log_id" value
 * @method AmSmsLog setMobileNumber()    Sets the current record's "mobile_number" value
 * @method AmSmsLog setMessage()         Sets the current record's "message" value
 * @method AmSmsLog setSendedDate()      Sets the current record's "sended_date" value
 * @method AmSmsLog setActivityLogId()   Sets the current record's "activity_log_id" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmSmsLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_sms_log');
        $this->hasColumn('mobile_number', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('message', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('sended_date', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('activity_log_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}