<?php

/**
 * BaseAmAction
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property Doctrine_Collection $AmObjectTypes
 * @property AmObjectActionConn $AmObjectActionConn
 * 
 * @method integer             getId()                 Returns the current record's "id" value
 * @method string              getName()               Returns the current record's "name" value
 * @method string              getBody()               Returns the current record's "body" value
 * @method Doctrine_Collection getAmObjectTypes()      Returns the current record's "AmObjectTypes" collection
 * @method AmObjectActionConn  getAmObjectActionConn() Returns the current record's "AmObjectActionConn" value
 * @method AmAction            setId()                 Sets the current record's "id" value
 * @method AmAction            setName()               Sets the current record's "name" value
 * @method AmAction            setBody()               Sets the current record's "body" value
 * @method AmAction            setAmObjectTypes()      Sets the current record's "AmObjectTypes" collection
 * @method AmAction            setAmObjectActionConn() Sets the current record's "AmObjectActionConn" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmAction extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_action');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmObjectType as AmObjectTypes', array(
             'refClass' => 'AmObjectActionConn',
             'local' => 'action_id',
             'foreign' => 'object_type_id'));

        $this->hasOne('AmObjectActionConn', array(
             'local' => 'id',
             'foreign' => 'action_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}