<?php

/**
 * BaseAmUserRelationList
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $total
 * @property integer $total_blocked
 * @property integer $total_active
 * @property integer $relation_id
 * @property AmUser $AmUser
 * 
 * @method integer            getUserId()        Returns the current record's "user_id" value
 * @method integer            getTotal()         Returns the current record's "total" value
 * @method integer            getTotalBlocked()  Returns the current record's "total_blocked" value
 * @method integer            getTotalActive()   Returns the current record's "total_active" value
 * @method integer            getRelationId()    Returns the current record's "relation_id" value
 * @method AmUser             getAmUser()        Returns the current record's "AmUser" value
 * @method AmUserRelationList setUserId()        Sets the current record's "user_id" value
 * @method AmUserRelationList setTotal()         Sets the current record's "total" value
 * @method AmUserRelationList setTotalBlocked()  Sets the current record's "total_blocked" value
 * @method AmUserRelationList setTotalActive()   Sets the current record's "total_active" value
 * @method AmUserRelationList setRelationId()    Sets the current record's "relation_id" value
 * @method AmUserRelationList setAmUser()        Sets the current record's "AmUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmUserRelationList extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_user_relation_list');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('total', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_blocked', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('total_active', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('relation_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}