<?php

/**
 * BaseAmObjectActionConn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $action_id
 * @property integer $object_type_id
 * @property string $slug
 * @property string $sentence_format
 * @property AmObjectType $AmObjectType
 * @property AmAction $AmAction
 * @property Doctrine_Collection $AmLogs
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getActionId()        Returns the current record's "action_id" value
 * @method integer             getObjectTypeId()    Returns the current record's "object_type_id" value
 * @method string              getSlug()            Returns the current record's "slug" value
 * @method string              getSentenceFormat()  Returns the current record's "sentence_format" value
 * @method AmObjectType        getAmObjectType()    Returns the current record's "AmObjectType" value
 * @method AmAction            getAmAction()        Returns the current record's "AmAction" value
 * @method Doctrine_Collection getAmLogs()          Returns the current record's "AmLogs" collection
 * @method AmObjectActionConn  setId()              Sets the current record's "id" value
 * @method AmObjectActionConn  setActionId()        Sets the current record's "action_id" value
 * @method AmObjectActionConn  setObjectTypeId()    Sets the current record's "object_type_id" value
 * @method AmObjectActionConn  setSlug()            Sets the current record's "slug" value
 * @method AmObjectActionConn  setSentenceFormat()  Sets the current record's "sentence_format" value
 * @method AmObjectActionConn  setAmObjectType()    Sets the current record's "AmObjectType" value
 * @method AmObjectActionConn  setAmAction()        Sets the current record's "AmAction" value
 * @method AmObjectActionConn  setAmLogs()          Sets the current record's "AmLogs" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmObjectActionConn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_object_action_conn');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('action_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('object_type_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('slug', 'string', 100, array(
             'type' => 'string',
             'unique' => true,
             'length' => 100,
             ));
        $this->hasColumn('sentence_format', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmObjectType', array(
             'local' => 'object_type_id',
             'foreign' => 'id'));

        $this->hasOne('AmAction', array(
             'local' => 'action_id',
             'foreign' => 'id'));

        $this->hasMany('AmActivityLog as AmLogs', array(
             'local' => 'id',
             'foreign' => 'object_action_conn_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}