<?php

/**
 * BaseAmJobExperience
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $body
 * @property string $company_name
 * @property timestamp $start_date
 * @property timestamp $end_date
 * @property string $ended_reason
 * @property integer $user_id
 * @property AmUser $AmUser
 * 
 * @method string          getName()         Returns the current record's "name" value
 * @method string          getBody()         Returns the current record's "body" value
 * @method string          getCompanyName()  Returns the current record's "company_name" value
 * @method timestamp       getStartDate()    Returns the current record's "start_date" value
 * @method timestamp       getEndDate()      Returns the current record's "end_date" value
 * @method string          getEndedReason()  Returns the current record's "ended_reason" value
 * @method integer         getUserId()       Returns the current record's "user_id" value
 * @method AmUser          getAmUser()       Returns the current record's "AmUser" value
 * @method AmJobExperience setName()         Sets the current record's "name" value
 * @method AmJobExperience setBody()         Sets the current record's "body" value
 * @method AmJobExperience setCompanyName()  Sets the current record's "company_name" value
 * @method AmJobExperience setStartDate()    Sets the current record's "start_date" value
 * @method AmJobExperience setEndDate()      Sets the current record's "end_date" value
 * @method AmJobExperience setEndedReason()  Sets the current record's "ended_reason" value
 * @method AmJobExperience setUserId()       Sets the current record's "user_id" value
 * @method AmJobExperience setAmUser()       Sets the current record's "AmUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmJobExperience extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_job_experience');
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
        $this->hasColumn('company_name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('start_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('end_date', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('ended_reason', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}