<?php

/**
 * BaseAmLoginHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $ip_address
 * @property string $access_type
 * @property AmUser $AmUser
 * 
 * @method integer        getUserId()      Returns the current record's "user_id" value
 * @method string         getIpAddress()   Returns the current record's "ip_address" value
 * @method string         getAccessType()  Returns the current record's "access_type" value
 * @method AmUser         getAmUser()      Returns the current record's "AmUser" value
 * @method AmLoginHistory setUserId()      Sets the current record's "user_id" value
 * @method AmLoginHistory setIpAddress()   Sets the current record's "ip_address" value
 * @method AmLoginHistory setAccessType()  Sets the current record's "access_type" value
 * @method AmLoginHistory setAmUser()      Sets the current record's "AmUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmLoginHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_login_history');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('ip_address', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('access_type', 'string', 50, array(
             'type' => 'string',
             'default' => 'Browser',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}