<?php

/**
 * BaseAmPost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $body
 * @property integer $topic_id
 * @property integer $user_id
 * @property integer $like_count
 * @property integer $dislike_count
 * @property boolean $is_blocked
 * @property AmTopic $AmTopic
 * @property AmUser $AmUser
 * 
 * @method string  getName()          Returns the current record's "name" value
 * @method string  getBody()          Returns the current record's "body" value
 * @method integer getTopicId()       Returns the current record's "topic_id" value
 * @method integer getUserId()        Returns the current record's "user_id" value
 * @method integer getLikeCount()     Returns the current record's "like_count" value
 * @method integer getDislikeCount()  Returns the current record's "dislike_count" value
 * @method boolean getIsBlocked()     Returns the current record's "is_blocked" value
 * @method AmTopic getAmTopic()       Returns the current record's "AmTopic" value
 * @method AmUser  getAmUser()        Returns the current record's "AmUser" value
 * @method AmPost  setName()          Sets the current record's "name" value
 * @method AmPost  setBody()          Sets the current record's "body" value
 * @method AmPost  setTopicId()       Sets the current record's "topic_id" value
 * @method AmPost  setUserId()        Sets the current record's "user_id" value
 * @method AmPost  setLikeCount()     Sets the current record's "like_count" value
 * @method AmPost  setDislikeCount()  Sets the current record's "dislike_count" value
 * @method AmPost  setIsBlocked()     Sets the current record's "is_blocked" value
 * @method AmPost  setAmTopic()       Sets the current record's "AmTopic" value
 * @method AmPost  setAmUser()        Sets the current record's "AmUser" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmPost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_post');
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             'length' => '',
             ));
        $this->hasColumn('topic_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('like_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('dislike_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('is_blocked', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmTopic', array(
             'local' => 'topic_id',
             'foreign' => 'id'));

        $this->hasOne('AmUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}