<?php

/**
 * BaseAmShopOptionValue
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $option_id
 * @property string $name
 * @property string $image_name
 * @property AmShopOption $AmShopOption
 * @property Doctrine_Collection $AmShopProducts
 * @property Doctrine_Collection $AmShopProductOptionValueConn
 * 
 * @method integer             getId()                           Returns the current record's "id" value
 * @method integer             getOptionId()                     Returns the current record's "option_id" value
 * @method string              getName()                         Returns the current record's "name" value
 * @method string              getImageName()                    Returns the current record's "image_name" value
 * @method AmShopOption        getAmShopOption()                 Returns the current record's "AmShopOption" value
 * @method Doctrine_Collection getAmShopProducts()               Returns the current record's "AmShopProducts" collection
 * @method Doctrine_Collection getAmShopProductOptionValueConn() Returns the current record's "AmShopProductOptionValueConn" collection
 * @method AmShopOptionValue   setId()                           Sets the current record's "id" value
 * @method AmShopOptionValue   setOptionId()                     Sets the current record's "option_id" value
 * @method AmShopOptionValue   setName()                         Sets the current record's "name" value
 * @method AmShopOptionValue   setImageName()                    Sets the current record's "image_name" value
 * @method AmShopOptionValue   setAmShopOption()                 Sets the current record's "AmShopOption" value
 * @method AmShopOptionValue   setAmShopProducts()               Sets the current record's "AmShopProducts" collection
 * @method AmShopOptionValue   setAmShopProductOptionValueConn() Sets the current record's "AmShopProductOptionValueConn" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmShopOptionValue extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_shop_option_value');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('image_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmShopOption', array(
             'local' => 'option_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasMany('AmShopProduct as AmShopProducts', array(
             'refClass' => 'AmShopProductOptionValueConn',
             'local' => 'value_id',
             'foreign' => 'product_id'));

        $this->hasMany('AmShopProductOptionValueConn', array(
             'local' => 'id',
             'foreign' => 'value_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}