<?php

/**
 * BaseAmShopCategoryGroupConn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $group_id
 * @property integer $shop_category_id
 * @property integer $product_count
 * @property integer $created_user_id
 * @property AmUser $AmUser
 * @property AmGroup $AmGroup
 * @property AmShopCategory $AmShopCategory
 * 
 * @method integer                 getGroupId()          Returns the current record's "group_id" value
 * @method integer                 getShopCategoryId()   Returns the current record's "shop_category_id" value
 * @method integer                 getProductCount()     Returns the current record's "product_count" value
 * @method integer                 getCreatedUserId()    Returns the current record's "created_user_id" value
 * @method AmUser                  getAmUser()           Returns the current record's "AmUser" value
 * @method AmGroup                 getAmGroup()          Returns the current record's "AmGroup" value
 * @method AmShopCategory          getAmShopCategory()   Returns the current record's "AmShopCategory" value
 * @method AmShopCategoryGroupConn setGroupId()          Sets the current record's "group_id" value
 * @method AmShopCategoryGroupConn setShopCategoryId()   Sets the current record's "shop_category_id" value
 * @method AmShopCategoryGroupConn setProductCount()     Sets the current record's "product_count" value
 * @method AmShopCategoryGroupConn setCreatedUserId()    Sets the current record's "created_user_id" value
 * @method AmShopCategoryGroupConn setAmUser()           Sets the current record's "AmUser" value
 * @method AmShopCategoryGroupConn setAmGroup()          Sets the current record's "AmGroup" value
 * @method AmShopCategoryGroupConn setAmShopCategory()   Sets the current record's "AmShopCategory" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmShopCategoryGroupConn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_shop_category_group_conn');
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('shop_category_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('product_count', 'integer', 4, array(
             'type' => 'integer',
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('created_user_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmUser', array(
             'local' => 'created_user_id',
             'foreign' => 'id'));

        $this->hasOne('AmGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('AmShopCategory', array(
             'local' => 'shop_category_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}