<?php

/**
 * BaseAmShopProductOptionValueConn
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property integer $option_id
 * @property integer $value_id
 * @property integer $quantity
 * @property AmShopProduct $AmShopProduct
 * @property AmShopOptionValue $AmShopOptionValue
 * @property AmShopOption $AmShopOption
 * 
 * @method integer                      getProductId()         Returns the current record's "product_id" value
 * @method integer                      getOptionId()          Returns the current record's "option_id" value
 * @method integer                      getValueId()           Returns the current record's "value_id" value
 * @method integer                      getQuantity()          Returns the current record's "quantity" value
 * @method AmShopProduct                getAmShopProduct()     Returns the current record's "AmShopProduct" value
 * @method AmShopOptionValue            getAmShopOptionValue() Returns the current record's "AmShopOptionValue" value
 * @method AmShopOption                 getAmShopOption()      Returns the current record's "AmShopOption" value
 * @method AmShopProductOptionValueConn setProductId()         Sets the current record's "product_id" value
 * @method AmShopProductOptionValueConn setOptionId()          Sets the current record's "option_id" value
 * @method AmShopProductOptionValueConn setValueId()           Sets the current record's "value_id" value
 * @method AmShopProductOptionValueConn setQuantity()          Sets the current record's "quantity" value
 * @method AmShopProductOptionValueConn setAmShopProduct()     Sets the current record's "AmShopProduct" value
 * @method AmShopProductOptionValueConn setAmShopOptionValue() Sets the current record's "AmShopOptionValue" value
 * @method AmShopProductOptionValueConn setAmShopOption()      Sets the current record's "AmShopOption" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmShopProductOptionValueConn extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_shop_product_option_value_conn');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('value_id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('quantity', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmShopProduct', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('AmShopOptionValue', array(
             'local' => 'value_id',
             'foreign' => 'id',
             'onDelete' => 'cascade'));

        $this->hasOne('AmShopOption', array(
             'local' => 'option_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}