<?php

/**
 * BaseAmVideoType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property Doctrine_Collection $AmVideos
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getBody()     Returns the current record's "body" value
 * @method Doctrine_Collection getAmVideos() Returns the current record's "AmVideos" collection
 * @method AmVideoType         setId()       Sets the current record's "id" value
 * @method AmVideoType         setName()     Sets the current record's "name" value
 * @method AmVideoType         setBody()     Sets the current record's "body" value
 * @method AmVideoType         setAmVideos() Sets the current record's "AmVideos" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmVideoType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_video_type');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmVideo as AmVideos', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}