<?php

/**
 * BaseAmUserEducation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $group_id
 * @property string $profession
 * @property string $school_name
 * @property integer $start_year
 * @property integer $education_level_id
 * @property AmUser $AmUser
 * @property AmGroup $AmGroup
 * @property AmEducationLevel $AmEducationLevel
 * 
 * @method integer          getId()                 Returns the current record's "id" value
 * @method integer          getUserId()             Returns the current record's "user_id" value
 * @method integer          getGroupId()            Returns the current record's "group_id" value
 * @method string           getProfession()         Returns the current record's "profession" value
 * @method string           getSchoolName()         Returns the current record's "school_name" value
 * @method integer          getStartYear()          Returns the current record's "start_year" value
 * @method integer          getEducationLevelId()   Returns the current record's "education_level_id" value
 * @method AmUser           getAmUser()             Returns the current record's "AmUser" value
 * @method AmGroup          getAmGroup()            Returns the current record's "AmGroup" value
 * @method AmEducationLevel getAmEducationLevel()   Returns the current record's "AmEducationLevel" value
 * @method AmUserEducation  setId()                 Sets the current record's "id" value
 * @method AmUserEducation  setUserId()             Sets the current record's "user_id" value
 * @method AmUserEducation  setGroupId()            Sets the current record's "group_id" value
 * @method AmUserEducation  setProfession()         Sets the current record's "profession" value
 * @method AmUserEducation  setSchoolName()         Sets the current record's "school_name" value
 * @method AmUserEducation  setStartYear()          Sets the current record's "start_year" value
 * @method AmUserEducation  setEducationLevelId()   Sets the current record's "education_level_id" value
 * @method AmUserEducation  setAmUser()             Sets the current record's "AmUser" value
 * @method AmUserEducation  setAmGroup()            Sets the current record's "AmGroup" value
 * @method AmUserEducation  setAmEducationLevel()   Sets the current record's "AmEducationLevel" value
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmUserEducation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_user_education');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('group_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('profession', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('school_name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('start_year', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('education_level_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('AmGroup', array(
             'local' => 'group_id',
             'foreign' => 'id'));

        $this->hasOne('AmEducationLevel', array(
             'local' => 'education_level_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}