<?php

/**
 * BaseAmEducationLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $body
 * @property Doctrine_Collection $AmUserEducation
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getBody()            Returns the current record's "body" value
 * @method Doctrine_Collection getAmUserEducation() Returns the current record's "AmUserEducation" collection
 * @method AmEducationLevel    setId()              Sets the current record's "id" value
 * @method AmEducationLevel    setName()            Sets the current record's "name" value
 * @method AmEducationLevel    setBody()            Sets the current record's "body" value
 * @method AmEducationLevel    setAmUserEducation() Sets the current record's "AmUserEducation" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmEducationLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_education_level');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('body', 'string', 500, array(
             'type' => 'string',
             'length' => 500,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('AmUserEducation', array(
             'local' => 'id',
             'foreign' => 'education_level_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}