<?php

/**
 * BaseAmUserRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $parent_id
 * @property AmUserRelation $Childs
 * @property Doctrine_Collection $Parent
 * @property Doctrine_Collection $AmUserToUser
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method integer             getParentId()     Returns the current record's "parent_id" value
 * @method AmUserRelation      getChilds()       Returns the current record's "Childs" value
 * @method Doctrine_Collection getParent()       Returns the current record's "Parent" collection
 * @method Doctrine_Collection getAmUserToUser() Returns the current record's "AmUserToUser" collection
 * @method AmUserRelation      setId()           Sets the current record's "id" value
 * @method AmUserRelation      setName()         Sets the current record's "name" value
 * @method AmUserRelation      setParentId()     Sets the current record's "parent_id" value
 * @method AmUserRelation      setChilds()       Sets the current record's "Childs" value
 * @method AmUserRelation      setParent()       Sets the current record's "Parent" collection
 * @method AmUserRelation      setAmUserToUser() Sets the current record's "AmUserToUser" collection
 * 
 * @package    sf_sandbox
 * @subpackage model
 * @author     Mipo Team
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAmUserRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('am_user_relation');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('parent_id', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('AmUserRelation as Childs', array(
             'local' => 'parent_id',
             'foreign' => 'id'));

        $this->hasMany('AmUserRelation as Parent', array(
             'local' => 'id',
             'foreign' => 'parent_id'));

        $this->hasMany('AmUserToUser', array(
             'local' => 'id',
             'foreign' => 'relation_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}