default:
  http_metas:
    content-type: text/html

  metas:
    title:        Mind Point
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [frontend/css/bootstrap.min.css, frontend/css/style.less:{ "rel": "stylesheet/less" }, frontend/css/eqstyle.less:{ "rel": "stylesheet/less" }]

  javascripts:    [jquery-1.8.2.min.js, jquery.form.js, /html/js/bootstrap.min.js, /html/css/less/less-1.3.3.min.js ]

  has_layout:     true
  layout:         layout
  
